<a href="https://colab.research.google.com/github/onexmaster/quantum_computing/blob/master/Hw_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from scipy.linalg import null_space
import numpy.random as npr

In [0]:
def test_minimal(M, coefficients):
  if coefficients.size == 0:
    return
  mult = np.eye(M.shape[0])
  sum = 0
  for i in range(len(coefficients)):
    sum += coefficients[i, 0] * mult
    mult = np.matmul(M, mult)
  return np.allclose(sum, 0)

In [0]:
def annihilate_min_deg_poly(M):
  n = M.shape[0]
  A = np.empty((n*n, 1))
  #Ravel Returns a contiguous flattened array.
  A[:, 0] = np.eye(n).ravel()
  M_curr = np.eye(n)
  for i in range(1, n+1):
    M_curr = np.matmul(M_curr, M)
    #Stack arrays in sequence horizontally (column wise).
    A = np.hstack((A, np.ravel(M_curr)[:, None]))
    coefficients = null_space(A)
    if test_minimal(M, coefficients):
      return coefficients

In [0]:
array = np.array([[5,-6,-6], [-1,4,2], [3,-6,-4]])
print('For the Matrix:')
print(array)
coefficients = annihilate_min_deg_poly(array)
print('Minimal Polynomial has the degree {}'.format(len(coefficients) - 1))
print('The coefficents of the Minimal Polynomial are as follows')
print(coefficients)

For the Matrix:
[[ 5 -6 -6]
 [-1  4  2]
 [ 3 -6 -4]]
Minimal Polynomial has the degree 2
The coefficents of the Minimal Polynomial are as follows
[[-0.53452248]
 [ 0.80178373]
 [-0.26726124]]


In [0]:
array = np.array([[1,0,0], [0,1,0], [0,0,1]])
print('For the Matrix:')
print(array)
coefficients = annihilate_min_deg_poly(array)
print('Minimal Polynomial has the degree {}'.format(len(coefficients) - 1))
print('The coefficents of the Minimal Polynomial are as follows')
print(coefficients)

For the Matrix:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Minimal Polynomial has the degree 1
The coefficents of the Minimal Polynomial are as follows
[[-0.70710678]
 [ 0.70710678]]


In [0]:
array = np.array([[0,1,0], [0,1,0], [0,0,1]])
print('For the Matrix:')
print(array)
coefficients = annihilate_min_deg_poly(array)
print('Minimal Polynomial has the degree {}'.format(len(coefficients) - 1))
print('The coefficents of the Minimal Polynomial are as follows')
print(coefficients)

For the Matrix:
[[0 1 0]
 [0 1 0]
 [0 0 1]]
Minimal Polynomial has the degree 2
The coefficents of the Minimal Polynomial are as follows
[[-0.        ]
 [ 0.70710678]
 [-0.70710678]]


In [0]:
array = np.array([[1,2], [3,4]])
print('For the Matrix:')
print(array)
coefficients = annihilate_min_deg_poly(array)
print('Minimal Polynomial has the degree {}'.format(len(coefficients) - 1))
print('The coefficents of the Minimal Polynomial are as follows')
print(coefficients)

For the Matrix:
[[1 2]
 [3 4]]
Minimal Polynomial has the degree 2
The coefficents of the Minimal Polynomial are as follows
[[-0.36514837]
 [-0.91287093]
 [ 0.18257419]]


In [0]:
#This is a 4x4 Jordan Block 
array = np.array([[5, 1, 0, 0], [0, 5, 1, 0], [0, 0, 5, 1], [0, 0, 0, 5]])
print('For the Matrix:')
print(array)
coefficients = annihilate_min_deg_poly(array)
print('Minimal Polynomial has the degree {}'.format(len(coefficients) - 1))
print('The coefficents of the Minimal Polynomial are as follows')
print(coefficients)

For the Matrix:
[[5 1 0 0]
 [0 5 1 0]
 [0 0 5 1]
 [0 0 0 5]]
Minimal Polynomial has the degree 4
The coefficents of the Minimal Polynomial are as follows
[[-0.76727499]
 [ 0.61382   ]
 [-0.184146  ]
 [ 0.0245528 ]
 [-0.00122764]]
